### ISSUE TITLE
Summary Section on Top 

### ISSUE THREAD

**Issue by angelayanpan** [lint-todo/ember-template-lint-formatter-todo#38]
It would be nice if

> Lint Todos (6 found)

can be at the bottom. not the top, because we have a super large number of toDos. thousands. so the Top line count requires a quite long scroll. or increased buffer size to view that information. 

![Screen Shot 2022-02-08 at 3 20 45 PM](https://user-images.githubusercontent.com/2455168/153070375-7b3334ed-92b3-49dd-b324-979b42e70b1f.png)
.

**Comment by scalvert** [comment]
Hey @angelayanpan, thanks for the suggestion. What would you think about having it listed both at the top/bottom? This way whether you're scrolling either way, you can see the counts.

**Comment by angelayanpan** [comment]
yes, that sounds good!
